### ISSUE TITLE
ITMS-90809: Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by mhdtouban** [codemotionapps/react-native-help-scout#7]
Our app got rejected on apple store since this library uses an older version of help scout ios SDK which still uses the deprecated UIWebView.. help scout has already solved this issue on v1.0.4 .. please update this RN SDK to use the latest version of the library v1.0.5

https://github.com/helpscout/beacon-ios-sdk/issues/37

**Comment by dimitarnestorov** [comment]
This library does not specify a version for Help Scout SDK for iOS. All you have to do to get the latest one is run `pod update` or delete `Podfile.lock`.
