### ISSUE TITLE
Beacon is not initialised - SDKInitException

### ISSUE THREAD

**Issue by omprakashnitdgp** [codemotionapps/react-native-help-scout#9]
I am initialising beacon in the application class OnCreate method with correct beacon_id.
However, it is throwing error 
com.helpscout.beacon.SDKInitException: Beacon not initialized. If you have disabled auto initialization via manifest metadata, ensure Beacon is manually init using Beacon.Builder().withContext(context)

Auto Initialisation is not disabled from the Manifest file.

IOS working fine with the same code base.
I tried to initialized Beacon from both Native & react-native JS side but each time it is throwing  SDKInitException

![Screenshot_1596544222](https://user-images.githubusercontent.com/17959436/89398809-36bcd080-d72f-11ea-888d-8a7d29d5e9cd.png)

**Comment by dimitarnestorov** [comment]
> I am initialising beacon in the application class OnCreate method with correct beacon_id.
You're initializing Beacon in Java/Kotlin?

**Comment by omprakashnitdgp** [comment]
I tried in different ways but each time throwing same Beacon initialization error.

Method 1.

import { Beacon } from 'react-native-help-scout'

Using this npm library, I tried to initialised in componentDidMount (`Beacon.init(beacon_id)`) but on page load its throws error.

This approach working fine on IOS platform but an error on android platform 

Method 2. 

Based on HelpScout documentation, I tried to integrate the android SDK & initialized beacon in Application Class OnCreate() method. I am getting the same initialization here also.

```
dependencies {
  implementation "com.helpscout:beacon-core:$beaconVersion"
  implementation "com.helpscout:beacon-ui:$beaconVersion"
}
```

```
Beacon beacon = new Beacon.Builder()
  .withBeaconId("YOUR_BEACON_ID_HERE")       
  .build();
```

https://developer.helpscout.com/beacon-2/android/


Any quick response is really helpful for me @dimitarnestorov

**Comment by dimitarnestorov** [comment]
I just created a brand new React Native project and added `react-native-help-scout` and it seems to work fine. Try with the latest version of Beacon. To do so open `android/app/build.gradle` and add `rootProject.ext.helpscoutBeacon = "2.1.2"` before `apply from: "../../node_modules/react-native/react.gradle"`. You don't need to call `Beacon.init` on `componentDidMount`, you can do it outside of any component. Don't use method 2.

**Comment by omprakashnitdgp** [comment]
No luck @dimitarnestorov 

Applied your steps but getting the same error. 

Can you please explain in details what is going on inside your project 

Thanks

**Comment by dimitarnestorov** [comment]
I can't reproduce this error myself. I can help if you make a small example repo where you can reproduce it.
